# Generated by Django 6.0.6 on 2026-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_workspaceinvite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Role name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list, verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Invited email'),
        ),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
