# Generated by Django 6.0.6 on 2026-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_rename_seed_roles_to_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
