# Generated by Django 6.0.6 on 2026-06-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_workspaceinvite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Timezone'),
        ),
    ]
