# Generated by Django 6.0.6 on 2026-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_workspaceinvite_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
