# Generated by Django 6.0.6 on 2026-06-09 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_schema', models.CharField(blank=True, db_index=True, max_length=63, verbose_name='Workspace schema')),
                ('workspace_name', models.CharField(blank=True, max_length=255, verbose_name='Workspace name')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Action')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Resource type')),
                ('resource_id', models.CharField(blank=True, max_length=255, verbose_name='Resource ID')),
                ('detail', models.JSONField(default=dict, verbose_name='Detail')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
